export enum ScreenNames {
  DRAWER_STACK = 'DRAWER_STACK',
  TAB_BAR_STACK = 'TAB_BAR_STACK',
  LOGGED_IN_STACK = 'LOGGED_IN_STACK',
  LOGGED_OUT_STACK = 'LOGGED_OUT_STACK', 
  LOGIN_PAGE = 'LOGIN_PAGE',
  REGISTRATION_PAGE = 'REGISTRATION_PAGE',
  HOME_PAGE = 'HOME_PAGE',
  TASKS_PAGE = 'TASKS_PAGE', 
  FAVORITE_PAGE = 'FAVORITE_PAGE',  
}