export enum ScreenNames {
  DRAWER_STACK = 'DRAWER_STACK',
  TASK_TAB_BAR_STACK = 'TASK_TAB_BAR_STACK',  
  LOGGED_IN_STACK = 'LOGGED_IN_STACK',
  LOGGED_OUT_STACK = 'LOGGED_OUT_STACK', 

  LOGIN_PAGE = 'LOGIN_PAGE',  
  REGISTRATION_PAGE = 'REGISTRATION_PAGE',
  
  HOME_PAGE = 'HOME_PAGE',
  ALL_TASKS_PAGE = 'ALL_TASKS_PAGE', 
  MARKED_TASKS_PAGE = 'MARKED_TASKS_PAGE', 
  ADD_TASK_PAGE = 'ADD_TASK_PAGE',
  UPDATE_TASK_PAGE = 'UPDATE_TASK_PAGE',
  FILTERS_SETTINGS_PAGE = 'FILTERS_SETTINGS_PAGE',
  DETAILS_TASK_PAGE = 'DETAILS_TASK_PAGE',
}